jwt.secret : adf3a1f465asdf184EAGKEG%W%$fdlmkndbfvklm

server:
  port: 8686
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 123456
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

  main:
    allow-circular-references: true


springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1
    show-extensions: false